vpc_cidr_block            = "10.0.0.0/16"
public_subnet_cidr_block  = ["10.0.0.0/24", "10.0.1.0/24"] # Example of a list of string.
private_subnet_cidr_block = ["10.0.2.0/24", "10.0.3.0/24"] # Example of a list of string.
db_subnet_cidr_block      = ["10.0.4.0/24", "10.0.5.0/24"] # Example of a list of string.
availability_zone         = ["us-west-1a", "us-west-1c"]   # Example of a list of string.
image_id                  = "ami-0945610b37068d87a"        # Amazon Linux 2 AMI (HVM), SSD Volume Type for us-west-1
instance_type             = "t2.micro"                     # free tier eligible instance type
key_name                  = "jupiter-keys"                 # key pair name "jupiter_keys"
db_username               = "admin"                        # master username for the RDS instance
db_allocated_storage      = 10                             # allocated storage in GB
db_engine_version         = "8.0"                          # MySQL engine version
db_instance_class         = "db.t3.micro"                  # db.t3.micro is free tier eligible
db_parameter_group_name   = "default.mysql8.0"             # default parameter group for MySQL 8.0
dns_zone_id               = "Z0527804LNVB6YESLM0K"
dns_name                  = "amkcircle.com"
ssl_policy                = "ELBSecurityPolicy-TLS13-1-2-Res-2021-06"                                             # this is the SSL policy to be used by the ALB
certificate_arn           = "arn:aws:acm:us-west-1:038777382011:certificate/b058eb25-9b36-47f2-aa8e-019da87f4329" # this is the ARN of the SSL certificate to be used by the ALB, we will create this in ACM module
